name = "eaas-platform-backend"
main = "src/index.ts"
compatibility_date = "2026-09-29"

[[d1_databases]]
binding = "DB"
database_name = "eaas_production_db"
database_id = "55daab76-8fbe-4da1-b075-bb04445469a5"
